devices:
  device 1:
    eom:
      ASRL INSTR:
        q: \r\n
        r: \n
    error: ERROR
    dialogues:
      - q: "*IDN?"
        r: Very Big Corporation of America, Jet Propulsor, SIM42, 4.2
      - q: Life?
        r: 42
      - q: No answer
    properties:
      frequency:
        default: 100.0
        getter:
          q: "FREQ?"
          r: "{:.3f}"
        setter:
          q: FREQ {:.3f}
          r: OK
          e: ERROR
        specs:
          min: 0
          max: 1000
          type: float

resources:
  ASRL1::INSTR:
    device: device 1
